GermanCourseRegistration.Web/Controllers/AdminCourseController.cs
using GermanCourseRegistration.Application.Messages.CourseMessages;
using GermanCourseRegistration.Application.Services;
using GermanCourseRegistration.Web.HelperServices;
using GermanCourseRegistration.Web.Mappings;
using GermanCourseRegistration.Web.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace GermanCourseRegistration.Web.Controllers;

[Authorize(Roles = "Admin")]
public class AdminCourseController : Controller
{
    private readonly IAdminCourseService adminCourseService;
    private readonly UserManager<IdentityUser> userManager;

    public AdminCourseController(
        IAdminCourseService adminCourseService,
        UserManager<IdentityUser> userManager)
    {
        this.adminCourseService = adminCourseService;
        this.userManager = userManager;
    }

    [HttpGet]
    public async Task<IActionResult> List()
    {
        var response = await adminCourseService.GetAllAsync();

        var viewModels = CourseMapping.MapToViewModels(response);

        return View(viewModels);
    }

    [HttpGet]
    public IActionResult Add()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Add(CourseView viewModel)
    {
        Guid loginId = await UserAccountService.GetCurrentUserId(userManager, User);

        var request = CourseMapping.MapToAddRequest(viewModel, loginId, DateTime.Now);

        var response = await adminCourseService.AddAsync(request);

        short key = Convert.ToInt16(response.IsTransactionSuccess);
        TempData[Notification.ModalMessage[key]] = response.Message;

        return RedirectToAction("List");
    }

    [HttpGet]
    public async Task<IActionResult> Edit(Guid id)
    {
        var response = await adminCourseService.GetByIdAsync(new GetCourseByIdRequest(id));

        if (response!.Course == null)
        {
            TempData[Notification.ModalMessage[0]] = "Something went wrong in retrieving the data";
            return RedirectToAction("List");
        }

        var viewModel = CourseMapping.MapToViewModel(response);

        return View(viewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(CourseView viewModel)
    {
        Guid loginId = await UserAccountService.GetCurrentUserId(userManager, User);

        var request = CourseMapping.MapToUpdateRequest(
            viewModel, loginId, DateTime.Now);

        var response = await adminCourseService.UpdateAsync(request);

        short key = Convert.ToInt16(response.IsTransactionSuccess);
        TempData[Notification.ModalMessage[key]] = response.Message;

        return RedirectToAction("List");
    }

    [HttpPost]
    public async Task<IActionResult> Delete(Guid id)
    {
        var response = await adminCourseService.DeleteAsync(
            new DeleteCourseRequest(id));

        short key = Convert.ToInt16(response.IsTransactionSuccess);
        TempData[Notification.ModalMessage[key]] = response.Message;

        return RedirectToAction("List");
    }
}

GermanCourseRegistration.Web/Controllers/AdminCourseMaterialController.cs
using GermanCourseRegistration.Application.Messages.CourseMaterialMessages;
using GermanCourseRegistration.Application.Services;
using GermanCourseRegistration.Web.HelperServices;
using GermanCourseRegistration.Web.Mappings;
using GermanCourseRegistration.Web.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;

namespace GermanCourseRegistration.Web.Controllers;

[Authorize(Roles = "Admin")]
public class AdminCourseMaterialController : Controller
{
    private readonly IAdminCourseMaterialService adminCourseMaterialService;
    private readonly UserManager<IdentityUser> userManager;

    public AdminCourseMaterialController(
        IAdminCourseMaterialService adminCourseMaterialService,
        UserManager<IdentityUser> userManager)
    {
        this.adminCourseMaterialService = adminCourseMaterialService;
        this.userManager = userManager;
    }

    [HttpGet]
    public async Task<IActionResult> List()
    {
        var response = await adminCourseMaterialService.GetAllAsync();

        var viewModels = CourseMaterialMapping.MapToViewModels(response);

        return View(viewModels);
    }

    [HttpGet]
    public IActionResult Add()
    {
        var viewModel = new CourseMaterialView();

        // Load the categories to select in UI
        LoadCategories(viewModel);

        return View(viewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Add(CourseMaterialView viewModel)
    {
        Guid loginId = await UserAccountService.GetCurrentUserId(userManager, User);

        var request = CourseMaterialMapping.MapToAddRequest(viewModel, loginId, DateTime.Now);

        var response = await adminCourseMaterialService.AddAsync(request);

        short key = Convert.ToInt16(response.IsTransactionSuccess);
        TempData[Notification.ModalMessage[key]] = response.Message;

        return RedirectToAction("List");
    }

    [HttpGet]
    public async Task<IActionResult> Edit(Guid id)
    {
        var response = await adminCourseMaterialService.GetByIdAsync(
            new GetCourseMaterialByIdRequest(id));

        if (response?.CourseMaterial == null)
        {
            TempData[Notification.ModalMessage[0]] = "Something went wrong in retrieving the data";
            return RedirectToAction("List");
        }

        var viewModel = CourseMaterialMapping.MapToViewModel(response);

        // Load the categories to select in UI
        LoadCategories(viewModel);

        return View(viewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(CourseMaterialView viewModel)
    {
        Guid loginId = await UserAccountService.GetCurrentUserId(userManager, User);

        var request = CourseMaterialMapping.MapToUpdateRequest(
            viewModel, loginId, DateTime.Now);

        var response = await adminCourseMaterialService.UpdateAsync(request);

        short key = Convert.ToInt16(response.IsTransactionSuccess);
        TempData[Notification.ModalMessage[key]] = response.Message;

        return RedirectToAction("List");
    }

    [HttpPost]
    public async Task<IActionResult> Delete(Guid id)
    {
        var response = await adminCourseMaterialService.DeleteAsync(
            new DeleteCourseMaterialRequest(id));

        short key = Convert.ToInt16(response.IsTransactionSuccess);
        TempData[Notification.ModalMessage[key]] = response.Message;

        return RedirectToAction("List");
    }

    private void LoadCategories(CourseMaterialView viewModel)
    {
        var categories = adminCourseMaterialService.GetCourseMaterialCategories();
        viewModel.AvailableCategories = categories.Select(c => new SelectListItem
        {
            Text = c,
            Value = c
        });
    }
}

GermanCourseRegistration.Web/Controllers/AdminCourseScheduleController.cs
using GermanCourseRegistration.Application.Services;
using GermanCourseRegistration.Web.HelperServices;
using GermanCourseRegistration.Web.Mappings;
using GermanCourseRegistration.Web.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;
using GermanCourseRegistration.Application.Messages.CourseOfferMessages;

namespace GermanCourseRegistration.Web.Controllers;

[Authorize(Roles = "Admin")]
public class AdminCourseScheduleController : Controller
{
    private readonly IAdminCourseService adminCourseService;
    private readonly IAdminCourseScheduleService adminCourseScheduleService;
    private readonly UserManager<IdentityUser> userManager;

    public AdminCourseScheduleController(
        IAdminCourseService adminCourseService,
        IAdminCourseScheduleService adminCourseScheduleService,
        UserManager<IdentityUser> userManager)
    {
        this.adminCourseService = adminCourseService;
        this.adminCourseScheduleService = adminCourseScheduleService;
        this.userManager = userManager;
    }

    [HttpGet]
    public async Task<IActionResult> List()
    {
        var response = await adminCourseScheduleService.GetAllAsync();

        var viewModels = CourseScheduleMapping.MapToViewModels(response);

        return View(viewModels);
    }

    [HttpGet]
    public async Task<IActionResult> Add()
    {
        var response = await adminCourseService.GetAllAsync();

        if (response == null || response.Courses == null || !response.Courses.Any())
        {
            TempData[Notification.ModalMessage[0]] = 
                "No courses available. Please create the course first.";
            return RedirectToAction("List");
        }

        var courseScheduleView = new CourseScheduleView();
        var courseViews = CourseMapping.MapToViewModels(response);

        LoadItemsForUI(courseScheduleView, courseViews);

        return View(courseScheduleView);
    }

    [HttpPost]
    public async Task<IActionResult> Add(CourseScheduleView viewModel)
    {
        Guid loginId = await UserAccountService.GetCurrentUserId(userManager, User);

        var request = CourseScheduleMapping.MapToAddRequest(viewModel, loginId, DateTime.Now);

        var response = await adminCourseScheduleService.AddAsync(request);

        short key = Convert.ToInt16(response.IsTransactionSuccess);
        TempData[Notification.ModalMessage[key]] = response.Message;

        return RedirectToAction("List");
    }

    [HttpGet]
    public async Task<IActionResult> Edit(Guid id)
    {
        var coursesResponse = await adminCourseService.GetAllAsync();
        var courseScheduleResponse = await adminCourseScheduleService.GetByIdAsync(
            new GetCourseOfferByIdRequest(id));

        if (coursesResponse == null || 
            coursesResponse.Courses == null || 
            !coursesResponse.Courses.Any() ||
            courseScheduleResponse == null ||
            courseScheduleResponse.CourseOffer == null)
        {
            TempData[Notification.ModalMessage[0]] = "No currently offered courses.";
            return RedirectToAction("List");
        }

        var courseScheduleView = CourseScheduleMapping.MapToViewModel(courseScheduleResponse);
        var courseViews = CourseMapping.MapToViewModels(coursesResponse);

        LoadItemsForUI(courseScheduleView, courseViews);

        return View(courseScheduleView);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(CourseScheduleView viewModel)
    {
        Guid loginId = await UserAccountService.GetCurrentUserId(userManager, User);

        var request = CourseScheduleMapping.MapToUpdateRequest(viewModel, loginId, DateTime.Now);

        var response = await adminCourseScheduleService.UpdateAsync(request);

        short key = Convert.ToInt16(response.IsTransactionSuccess);
        TempData[Notification.ModalMessage[key]] = response.Message;

        return RedirectToAction("List");
    }

    [HttpPost]
    public async Task<IActionResult> Delete(Guid id)
    {
        var response = await adminCourseScheduleService.DeleteAsync(
            new DeleteCourseOfferRequest(id));

        short key = Convert.ToInt16(response.IsTransactionSuccess);
        TempData[Notification.ModalMessage[key]] = response.Message;

        return RedirectToAction("List");
    }

    private void LoadItemsForUI(
        CourseScheduleView courseScheduleView, 
        IEnumerable<CourseView> courseViews)
    {
        // Load the drop down list items
        courseScheduleView.AvailableCourseLevels = courseViews.Select(c => new SelectListItem
        {
            Text = c.Level.ToString() + "." + c.Part.ToString(),
            Value = c.Id.ToString()
        });

        var classTypes = adminCourseScheduleService.GetAvailableClassTypes();
        courseScheduleView.AvailableClassTypes = classTypes.Select(c => new SelectListItem
        {
            Text = c,
            Value = c
        });

        // Load the days of the week
        courseScheduleView.DaysOfWeek = adminCourseScheduleService.GetDaysOfWeek();
    }
}

GermanCourseRegistration.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager

@{
    var successMessage = TempData["SuccessMessage"] as string;
    var errorMessage = TempData["ErrorMessage"] as string;

    var message = !string.IsNullOrEmpty(successMessage) ? successMessage :
                  !string.IsNullOrEmpty(errorMessage) ? errorMessage : "";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>German Course Registration</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GermanCourseRegistration.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <style>
        .custom-toggler.navbar-toggler {
            border-color: rgb(255,102,203);
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm bg-secondary mb-3">
            <div class="container-fluid">
                <!-- Logo -->
                <a class="navbar-brand"
                   asp-controller="Home"
                   asp-action="Index">
                    <i class="bi bi-journal-richtext text-info"></i>
                </a>
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#mainnavbar">
                    <i class="bi bi-list"></i>
                </button>
                <div class="collapse navbar-collapse" id="mainnavbar">
                    @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                    {
                        <ul class="navbar-nav me-auto">
                            <!-- Admin Actions -->
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white"
                                href="#"
                                role="button"
                                data-bs-toggle="dropdown">
                                    Admin
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item"
                                        asp-controller="AdminCourse"
                                        asp-action="List">
                                            Courses
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item"
                                        asp-controller="AdminCourseSchedule"
                                        asp-action="List">
                                            Course Schedules
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item"
                                        asp-controller="AdminCourseMaterial"
                                        asp-action="List">
                                            Course Materials
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item"
                                           asp-controller="AdminUser"
                                           asp-action="List">
                                            Users
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <span class="me-auto"></span>
                    }
                    @if (signInManager.IsSignedIn(User))
                    {
                        <div class="me-3 text-light">
                            @User?.Identity?.Name
                        </div>
                        <a class="btn btn-info mx-1 text-dark"
                           asp-area=""
                           asp-controller="Account"
                           asp-action="Logout">
                            <i class="bi bi-door-closed"></i> Logout
                        </a>
                    }
                    else
                    {
                        <a class="btn btn-info mx-1 text-dark"
                           asp-area=""
                           asp-controller="Account"
                           asp-action="Login">
                            <i class="bi bi-door-open"></i> Login
                        </a>
                        <a class="btn btn-info mx-1 text-dark"
                           asp-area=""
                           asp-controller="Account"
                           asp-action="Register">
                            <i class="bi bi-pen"></i> Register
                        </a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Modal to display success or failed message of added, edited, or deleted course material -->
    @if (!string.IsNullOrEmpty(message))
    {
        <div class="modal fade" id="messageModal">
            <div class="modal-dialog">
                <div class="modal-content">

                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h5 class="modal-title" id="messageModalLabel">@(!string.IsNullOrEmpty(successMessage) ? "Success" : "Error")</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">
                        @message
                    </div>
                </div>
            </div>
        </div>

        <!-- Call JavaScript to show the modal -->
        <script>
            $(document).ready(function () {
                $('#messageModal').modal('show');
            });
        </script>
    }

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GermanCourseRegistration.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>