GermanCourseRegistration.Web/Controllers/HomeController.cs
using GermanCourseRegistration.Application.Messages.RegistrationMessages;
using GermanCourseRegistration.Application.Services;
using GermanCourseRegistration.Web.Mappings;
using GermanCourseRegistration.Web.Models;
using GermanCourseRegistration.Web.Models.ViewModels;
using GermanCourseRegistration.Web.HelperServices;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GermanCourseRegistration.Web.Controllers;

public class HomeController : Controller
{
    private readonly IAdminCourseScheduleService adminCourseScheduleService;
    private readonly IRegistrationService registrationService;
    private readonly UserManager<IdentityUser> userManager;

    public HomeController(
        IAdminCourseScheduleService adminCourseScheduleService,
        IRegistrationService registrationService,
        UserManager<IdentityUser> userManager)
    {
        this.adminCourseScheduleService = adminCourseScheduleService;
        this.registrationService = registrationService;
        this.userManager = userManager;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
	{
        var courseScheduleViewModels = Enumerable.Empty<CourseScheduleView>();
        CourseScheduleForStudentView? courseScheduleForStudentModel = null;

        if (User.IsInRole("Admin"))
        {
            var response = await adminCourseScheduleService.GetAllAsync();
            courseScheduleViewModels = CourseScheduleMapping.MapToViewModels(response);
        }
        else if (User.IsInRole("User"))
        {
            Guid studentId = await UserAccountService.GetCurrentUserId(userManager, User);
            var studentRegistrationResponse = await registrationService.GetByStudentIdAsync(
                new GetRegistrationByStudentIdRequest(studentId));

            if (studentRegistrationResponse?.Registration?.CourseOffer != null)
            {
                courseScheduleForStudentModel = new CourseScheduleForStudentView()
                {
                    Name = studentRegistrationResponse.Registration.CourseOffer.Name,
                    ClassType = studentRegistrationResponse.Registration.CourseOffer.ClassType,
                    StartDate = studentRegistrationResponse.Registration.CourseOffer.StartDate,
                    EndDate = studentRegistrationResponse.Registration.CourseOffer.EndDate
                };
            }

        }

        var viewModels = (
            CourseScheduleViews: courseScheduleViewModels,
            CourseScheduleForStudentView: courseScheduleForStudentModel!);

        return View(viewModels);
    }

	public IActionResult Privacy()
	{
		return View();
	}

	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	public IActionResult Error()
	{
		return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
	}
}

GermanCourseRegistration.Web/Controllers/StudentPersonalInformationController.cs
using GermanCourseRegistration.Application.Messages.StudentMessages;
using GermanCourseRegistration.Application.Services;
using GermanCourseRegistration.Web.HelperServices;
using GermanCourseRegistration.Web.Mappings;
using GermanCourseRegistration.Web.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GermanCourseRegistration.Web.Controllers;

public class StudentPersonalInformationController : Controller
{
    private readonly IStudentService studentService;
    private readonly UserManager<IdentityUser> userManager;

    public StudentPersonalInformationController(
        IStudentService studentService,
        UserManager<IdentityUser> userManager)
    {
        this.studentService = studentService;
        this.userManager = userManager;
    }

    [HttpGet]
	public async Task<IActionResult> Add()
	{
        Guid loginId = await UserAccountService.GetCurrentUserId(userManager, User);

        var response = await studentService.GetByIdAsync(new GetStudentByIdRequest(loginId));

        bool isExistingStudent = response == null || response.Student == null ? false : true;

        var viewModel = isExistingStudent
            ? StudentPersonalInformationMapping.MapToViewModel(response!)
            : new StudentView();

        // Load the drop down list items, and properties
        var salutations = studentService.GetSalutations();
        viewModel.AvailableSalutations = salutations.Select(s => new SelectListItem
        {
            Text = s,
            Value = s
        });
        viewModel.IsExistingStudent = isExistingStudent;

        return View(viewModel);
	}

    [HttpPost]
    public async Task<IActionResult> Add(StudentView viewModel)
    {
        Guid loginId = await UserAccountService.GetCurrentUserId(userManager, User);

        if (!viewModel.IsExistingStudent)
        {
            var request = StudentPersonalInformationMapping.MapToAddRequest(
                viewModel, loginId, DateTime.Now);

            await studentService.AddAsync(request);
        }
        else
        {
            var request = StudentPersonalInformationMapping.MapToUpdateRequest(
                viewModel, loginId, DateTime.Now);

            await studentService.UpdateAsync(request);
        }

        return RedirectToAction("Add", "CourseSelection");
    }
}

GermanCourseRegistration.Web/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager
@model (IEnumerable<GermanCourseRegistration.Web.Models.ViewModels.CourseScheduleView> CourseScheduleViews, GermanCourseRegistration.Web.Models.ViewModels.CourseScheduleForStudentView CourseScheduleViewForStudent)

@if (signInManager.IsSignedIn(User))
{
    @if (User.IsInRole("Admin"))
    {
        <div class="container mb-3 d-flex justify-content-center">
            <h3>Course Schedule List</h3>
        </div>
    }
    else
    {
        <div class="container mb-3 d-flex justify-content-center">
            <h3>My Course</h3>
        </div>
        <div class="container mb-3 d-flex justify-content-end">
            <a class="btn btn-info ms-2"
               asp-controller="StudentPersonalInformation"
               asp-action="Add">
                <i class="bi bi-pen"></i> Register for a new course
            </a>
        </div>
    }
}
                    
<div class="container mb-3">
    @if (signInManager.IsSignedIn(User))
    {
        @if (User.IsInRole("Admin"))
        {
            @if (Model.CourseScheduleViews != null && Model.CourseScheduleViews.Any())
            {
                <table class="table table-hover">
                    <thead>
                        <tr class="table-light">
                            <th>Course Level</th>
                            <th>Course Name</th>
                            <th>Class Type</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var schedule in Model.CourseScheduleViews)
                        {
                            <tr>
                                <td>
                                    @if (schedule.Course != null)
                                    {
                                        @(schedule.Course.Level.ToString() +
                                            "." +
                                            schedule.Course.Part.ToString())
                                    }
                                    else
                                    {
                                        <span>-</span>
                                    }
                                </td>
                                <td>@schedule.Name</td>
                                <td>@schedule.ClassType</td>
                                <td>@schedule.StartDate</td>
                                <td>@schedule.EndDate</td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <p>No course schedules found!</p>
            }
        }
        else
        {
            @if (Model.CourseScheduleViewForStudent != null)
            {
                <table class="table table-hover">
                    <thead>
                        <tr class="table-light">
                            <th>Name</th>
                            <th>Class Type</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@Model.CourseScheduleViewForStudent.Name</td>
                            <td>@Model.CourseScheduleViewForStudent.ClassType</td>
                            <td>@Model.CourseScheduleViewForStudent.StartDate</td>
                            <td>@Model.CourseScheduleViewForStudent.EndDate</td>
                        </tr>
                    </tbody>
                </table>
            }
            else
            {
                <p>No registered course found!</p>
            }  
        }
    }
    else
    {
        <h2>Welcome to German Course Registration.</h2>
        <p>Please <b>Log in</b> to start registration for your class.</p>
    } 
</div>